# Generated by Django 2.1 on 2018-08-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'permissions': (('can_manage_note', 'Can manage the own note'),)},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'permissions': (('can_manage_todolist', 'Can manage the own todoList'),)},
        ),
        migrations.AlterModelOptions(
            name='todothing',
            options={'permissions': (('can_manage_things_todo', 'Can manage things to do'),)},
        ),
    ]
